module.exports = {

	query_get_promo_info_full: "SELECT b.*, p.id as promo_id, p.name as promo_name, p.created_at, p.expired_at, p.description, p.count, bp.visible FROM ibero.branch_promotions bp INNER JOIN ibero.promotions p ON bp.id_promotion=p.id INNER JOIN ibero.branch b ON bp.id_branch=b.id WHERE bp.id_promotion=?;",
	query_get_branchs_by_id: "SELECT * FROM branch WHERE business_id=?",
	query_get_categories: "SELECT c.name, c.id_categories as id FROM categories c INNER JOIN business b WHERE c.id_categories=b.categorie",
	query_get_categories_by_business_type: "SELECT id_categories as id, name FROM categories WHERE id_business_type=?",
	query_get_business_order_by_name: "SELECT * FROM business WHERE active=1 ORDER BY name",
	query_get_business_by_state_order_by_name: "SELECT * FROM business WHERE state=? ORDER BY name",
    query_get_credential: "SELECT name, lastname, second_lastname, mat, photo, gender,career, active, email, street_number, suburb, postal_code, phone, mobile, business_name, business_type, position, day_start, month_start, year_start   from student WHERE id=?",
	query_get_business_and_branchs: "SELECT  b.logo, b.name,b.graduated, s.* FROM business b INNER JOIN branch s ON (b.id = s.business_id);",
	query_insert_branch: "INSERT INTO branch SET ?;",
    query_get_branchs: "SELECT * FROM branch WHERE business_id=?;",
    query_get_branch_by_id: "SELECT * FROM branch WHERE id=? LIMIT 1;",
	query_update_branch_by_id: "UPDATE branch SET name=?, latitude=?, longitude=?, address=? WHERE id=?;",
	query_update_promotion_by_id: "UPDATE promotions SET name=?, created_at=?, expired_at=?, description=? WHERE id=?;",
	query_get_devices: "SELECT * FROM devices;",
	query_get_business_by_id: "SELECT id, name, phone, discount_description, business_type, logo, graduated FROM business WHERE id=?;",
    query_get_promos_by_id_business: "SELECT id, name, description, business_id FROM promotions WHERE business_id=?;",
	query_get_branch_promotion_by_encrypt: "SELECT count FROM branch_promotions WHERE encrypt=?;",
    query_insert_student_promotion: "INSERT INTO student_promotions SET ?;",
	query_get_full_promotion: "SELECT b.name AS branch, b.address AS branch_address, b.latitude, b.longitude,s.count, s.active, p.name AS promo, p.description FROM branch b INNER JOIN branch_promotions s ON b.id = s.id_branch INNER JOIN promotions p ON p.id = s.id_promotion WHERE s.encrypt=? and s.active=? AND ? BETWEEN p.created_at AND p.expired_at;",
	query_update_count_in_branch_promotion: "UPDATE branch_promotions SET count=count+1  WHERE encrypt=?;",
	query_get_branch_promotion: "SELECT * FROM branch_promotions WHERE id_branch=? AND id_promotion=? LIMIT 1;",
	query_get_full_branch_promotions_by_id_business: "SELECT b.name as name_branch, b.address, s. * , p.name, p.description FROM branch b INNER JOIN branch_promotions s ON b.id = s.id_branch INNER JOIN promotions p ON p.id = s.id_promotion WHERE b.business_id=? AND s.visible=1;",
	query_get_branches_by_promotion: "SELECT b.address, b.latitude, b.longitude, b.name, c.graduated FROM branch_promotions p INNER JOIN branch b ON p.id_branch = b.id  INNER JOIN business c ON c.id = b.business_id WHERE p.id_promotion=? AND p.visible=1;"
};